{
    'name' : 'library management',
    'version' : '15.0.0.1.0',
    'description' : 'library management module details',
    'depends' : ['mail','sale','contacts'],
    'data' : [
        'security/ir.model.access.csv',
        'data/ir_sequence_book.xml',
        'data/mail_template_data.xml',
        'data/issue_book_data.xml',
        'views/book_author_info.xml',
        'views/book_details_info.xml',
        'views/register_books_info.xml',
        'views/issue_book_info.xml',
        'views/register_date_info.xml',
        'views/sale_order_view_inherit.xml',
        'views/book_type_info.xml',
        'views/res_partner_view_inherit.xml',
        'wizard/issue_date_wizard.xml',
        'wizard/issue_book_wizard.xml',
        'wizard/pass_context_wizard.xml',
        'report/register_date_info_report.xml',
        'report/register_date_info_report_templates.xml',
        'report/issue_book_info_report.xml',
        'report/issue_book_info_report_templates.xml',
    ],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
}